apiVersion: v1
kind: Service
metadata:
  name: streamnow-api
  namespace: streamnow
spec:
  selector:
    app: streamnow-api
  ports:
    - port: 4000
      targetPort: http
      name: http
  type: ClusterIP


