apiVersion: v1
kind: Service
metadata:
  name: streamnow-frontend
  namespace: streamnow
spec:
  selector:
    app: streamnow-frontend
  ports:
    - port: 3000
      targetPort: http
      name: http
  type: ClusterIP


