apiVersion: v1
kind: Service
metadata:
  name: streamnow-home-server
  namespace: streamnow
spec:
  selector:
    app: streamnow-home-server
  ports:
    - port: 4300
      targetPort: http
      name: http
  type: ClusterIP


